# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

env:
  global:
    - WP_TESTS_DIR=/tmp/wordpress-tests-lib
  # Specify versions of WordPress to test against
  # WP_VERSION = WordPress version number (or "latest")
  # WP_MULTISITE = whether to test multisite (use either "0" or "1")
  matrix:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1

# Use PHPUnit 6 instead of PHPUnit 7 which Travis loads by default
# with PHP 7.2. WordPress doesn't support PHPUnit 7.
before_script:
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then wget -O phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then wget -O phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then chmod a+x phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then chmod a+x phpunit; fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.2" ]]; then ./phpunit; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then ./phpunit; fi

# Reduce mail notifications by Travis CI to a minimum
notifications:
  email:
    on_success: change
    on_failure: always
